import {
  KIPU_BANK_CAP,
  KIPU_BANK_MAX_SINGLE_WITHDRAW_LIMIT,
  KIPU_BANK_OWNER_ADDRESS,
  KIPU_BANK_ETH_USD_PRICE_FEED,
  KIPU_BANK_USDC_TOKEN_ADDRESS
} from '../config/env';

if (
  !KIPU_BANK_CAP ||
  !KIPU_BANK_MAX_SINGLE_WITHDRAW_LIMIT ||
  !KIPU_BANK_OWNER_ADDRESS ||
  !KIPU_BANK_ETH_USD_PRICE_FEED ||
  !KIPU_BANK_USDC_TOKEN_ADDRESS
) {
  throw new Error('Constructor values not provided in .env.');
}

export default [
  KIPU_BANK_CAP,
  KIPU_BANK_MAX_SINGLE_WITHDRAW_LIMIT,
  KIPU_BANK_OWNER_ADDRESS,
  KIPU_BANK_ETH_USD_PRICE_FEED,
  KIPU_BANK_USDC_TOKEN_ADDRESS
];
